"""grupo-materia: campo banda

Revision ID: 46ce0f6b78a8
Revises: 98aee423a2cc
Create Date: 2026-09-09 23:58:53.762641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46ce0f6b78a8'
down_revision = '98aee423a2cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grupos_materia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('banda', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grupos_materia', schema=None) as batch_op:
        batch_op.drop_column('banda')

    # ### end Alembic commands ###
