"""bloqueos: quitar campo motivo

Revision ID: 559459c93210
Revises: f02114e926bf
Create Date: 2026-09-09 23:38:30.087711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '559459c93210'
down_revision = 'f02114e926bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bloqueos', schema=None) as batch_op:
        batch_op.drop_column('motivo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bloqueos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('motivo', sa.VARCHAR(length=200), nullable=True))

    # ### end Alembic commands ###
