"""profesor: jornada/guardia/chl; materia: departamento; grupo_materia: horas_semana; asignaciones

Revision ID: 80daa5577d4e
Revises: d323ea99e86b
Create Date: 2026-09-09 17:38:06.468271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80daa5577d4e'
down_revision = 'd323ea99e86b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grupos_materia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('horas_semana', sa.Integer(), nullable=True))

    with op.batch_alter_table('materias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('departamento_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_materias_departamento_id', 'departamentos', ['departamento_id'], ['id'])

    with op.batch_alter_table('profesores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jornada_completa', sa.Boolean(), nullable=False, server_default=sa.true()))
        batch_op.add_column(sa.Column('guardia_tipo', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profesores', schema=None) as batch_op:
        batch_op.drop_column('guardia_tipo')
        batch_op.drop_column('jornada_completa')

    with op.batch_alter_table('materias', schema=None) as batch_op:
        batch_op.drop_constraint('fk_materias_departamento_id', type_='foreignkey')
        batch_op.drop_column('departamento_id')

    with op.batch_alter_table('grupos_materia', schema=None) as batch_op:
        batch_op.drop_column('horas_semana')

    # ### end Alembic commands ###
