"""aulas: quitar campo capacidad

Revision ID: be5182ecbdf7
Revises: 80daa5577d4e
Create Date: 2026-09-09 19:36:11.209828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be5182ecbdf7'
down_revision = '80daa5577d4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aulas', schema=None) as batch_op:
        batch_op.drop_column('capacidad')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aulas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capacidad', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
