"""bloqueos y configuracion del centro

Revision ID: f02114e926bf
Revises: f296fe5ef864
Create Date: 2026-09-09 23:32:24.054447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f02114e926bf'
down_revision = 'f296fe5ef864'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_grupos_materia')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_grupos_materia',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('codigo', sa.VARCHAR(length=40), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=150), nullable=True),
    sa.Column('tipo', sa.VARCHAR(length=60), nullable=False),
    sa.Column('materia_id', sa.INTEGER(), nullable=False),
    sa.Column('curso_texto', sa.VARCHAR(length=200), nullable=True),
    sa.Column('curso_nivel', sa.VARCHAR(length=40), nullable=True),
    sa.Column('grupos_letras', sa.VARCHAR(length=80), nullable=True),
    sa.Column('origen', sa.VARCHAR(length=10), nullable=False),
    sa.Column('revisado', sa.BOOLEAN(), nullable=False),
    sa.Column('horas_semana', sa.INTEGER(), nullable=True),
    sa.Column('departamento_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['departamento_id'], ['departamentos.id'], name=op.f('fk_grupos_materia_departamento_id')),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    # ### end Alembic commands ###
